# https://segmentfault.com/a/1190000017307713 分布式websocket解决方案
server:
  port: 8787

spring:
  application:
    name: gateway
  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: esbot2019
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: ws-service
          uri: lb://ws-service
          predicates:
          - Path=/ws-service/**
    loadbalancer:
      ribbon:
        enabled: false

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    service-url:
      defaultZone: http://127.0.0.1:8777/eureka/

# 运维监控配置
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
