server:
  port: 8080
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    # MYSQL 5 驱动：com.mysql.jdbc.Driver，MYSQL 6+ 驱动：com.mysql.cj.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.55.157.135:3306/test?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false
    username: root
    password: Hxopen123

    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      max-lifetime: 180000
      connection-timeout: 30000
      connection-test-query: SELECT 1 FROM dual
  activiti:
    # 自动部署验证设置
    check-process-definitions: true
    # 是否每次都要更新数据库
    database-schema-update: true
    process-definition-location-prefix: classpath:/processes/
    history-level: full
    db-identity-used: false
    db-history-used: true


mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: is_deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true