spring:
  application:
    name: netty-websocket
  redis:
    host: 127.0.0.1
    port: 6379
  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: esbot2019
  jms:
    pub-sub-domain: true

server:
  port: 5858
