server:
  port: 8080

spring:
  application:
    name: security
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    # MYSQL 5 驱动：com.mysql.jdbc.Driver，MYSQL 6+ 驱动：com.mysql.cj.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.55.157.135:3306/test?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false
    username: root
    password: Hxopen123

    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      max-lifetime: 180000
      connection-timeout: 30000
      connection-test-query: SELECT 1 FROM dual


  redis:
    host: 127.0.0.1
    port: 6379
    database: 0

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: is_deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true

# 缓存前缀
cache:
  prefix: hx_

# jwt配置
jwt:
  token:
    header: Authorization
    secret: 123ialsd8231
    # 过期时间 分钟
    expireTime: 30